name: Bug Report
description: Report an issue with an Orbit ecosystem project
title: "[BUG] "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report an issue!
  - type: input
    id: version
    attributes:
      label: Version
      description: Which version of the project are you using?
      placeholder: v1.0.0
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: Please clearly describe the issue.
    validations:
      required: true
  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: How can we reproduce this bug?
    validations:
      required: true
